services:
  - type: web
    name: HachYoJobs.com
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python manage.py runserver 0.0.0.0:$PORT
    envVars:
  - key: DJANGO_SETTINGS_MODULE
    value: backend.settings
  - key: SECRET_KEY
    value: 'django-insecure-2+=k2w)cea-!437@fzp(_0j18kdm=^^3&-u*acma7+ha%qe9dp'
  - key: DEBUG
    value: "False"