services:
  - type: web
    name: HachYoJobs.com
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.job_recommender.wsgi:application
    envVars:
  - key: DJANGO_SETTINGS_MODULE
    value: backend.job_recommender.settings
  - key: SECRET_KEY
    value: 'django-insecure-2+=k2w)cea-!437@fzp(_0j18kdm=^^3&-u*acma7+ha%qe9dp'
  - key: DEBUG
    value: "False"